# Generated by Django 3.0.6 on 2020-05-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prof_pic',
            field=models.ImageField(default='default.jpg', upload_to='~/profile_pics'),
        ),
    ]
