# Generated by Django 3.0.6 on 2020-05-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200525_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prof_pic',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='picture'),
        ),
    ]
