# Generated by Django 3.0.5 on 2020-04-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormitoryManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dormitory',
            options={'verbose_name': 'Dormitory', 'verbose_name_plural': 'Dormitories'},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'verbose_name': 'Floor', 'verbose_name_plural': 'Floors'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterField(
            model_name='floor',
            name='Floor_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='floor',
            name='Number_of_rooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='Amount_of_places',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='Room_number',
            field=models.IntegerField(),
        ),
    ]
