# Generated by Django 3.0.5 on 2020-04-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormitoryManagement', '0002_auto_20200419_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitory',
            name='Amount_of_rooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='Dormitory_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='Floor_amount',
            field=models.IntegerField(),
        ),
    ]
